name: install-action
description: 'Specific action to install project and his environment'

inputs:
    architecture:
        description: 'Choice of architecture'
        default: x64
        required: false
    node_version:
        description: 'Version of node'
        default: 17
        required: false
    pnpm_version:
        description: 'Version of pnpm'
        default: 6.10.0
        required: false

# Add cache for pnpm / node / node_module?
runs:
    using: 'composite'
    steps:
        -
            name: '[GITHUB / OFFICIAL] Setup node'
            uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
            with:
                node-version: ${{ inputs.node_version }}
                architecture: ${{ inputs.architecture }}
        -
            name: '[PNPM / OFFICIAL] Setup PNPM'
            uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # v2.2.4
            with:
                version: ${{ inputs.pnpm_version }}
        -
            name: 'Install project'
            shell: sh
            run: pnpm install
        -
            name: 'Launch build'
            shell: sh
            run: pnpm run build
